# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: federated.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='federated.proto',
  package='hospital',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x66\x65\x64\x65rated.proto\x12\x08hospital\"+\n\x13UpdatedModelRequest\x12\x14\n\x0cglobal_model\x18\x01 \x01(\x0c\"3\n\x0cModelWeights\x12\x0f\n\x07weights\x18\x01 \x01(\x0c\x12\x12\n\nlocal_size\x18\x02 \x01(\x05\x32Z\n\x08Hospital\x12N\n\x13\x43omputeUpdatedModel\x12\x1d.hospital.UpdatedModelRequest\x1a\x16.hospital.ModelWeights\"\x00\x62\x06proto3'
)




_UPDATEDMODELREQUEST = _descriptor.Descriptor(
  name='UpdatedModelRequest',
  full_name='hospital.UpdatedModelRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='global_model', full_name='hospital.UpdatedModelRequest.global_model', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=72,
)


_MODELWEIGHTS = _descriptor.Descriptor(
  name='ModelWeights',
  full_name='hospital.ModelWeights',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='weights', full_name='hospital.ModelWeights.weights', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='local_size', full_name='hospital.ModelWeights.local_size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=125,
)

DESCRIPTOR.message_types_by_name['UpdatedModelRequest'] = _UPDATEDMODELREQUEST
DESCRIPTOR.message_types_by_name['ModelWeights'] = _MODELWEIGHTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UpdatedModelRequest = _reflection.GeneratedProtocolMessageType('UpdatedModelRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEDMODELREQUEST,
  '__module__' : 'federated_pb2'
  # @@protoc_insertion_point(class_scope:hospital.UpdatedModelRequest)
  })
_sym_db.RegisterMessage(UpdatedModelRequest)

ModelWeights = _reflection.GeneratedProtocolMessageType('ModelWeights', (_message.Message,), {
  'DESCRIPTOR' : _MODELWEIGHTS,
  '__module__' : 'federated_pb2'
  # @@protoc_insertion_point(class_scope:hospital.ModelWeights)
  })
_sym_db.RegisterMessage(ModelWeights)



_HOSPITAL = _descriptor.ServiceDescriptor(
  name='Hospital',
  full_name='hospital.Hospital',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=127,
  serialized_end=217,
  methods=[
  _descriptor.MethodDescriptor(
    name='ComputeUpdatedModel',
    full_name='hospital.Hospital.ComputeUpdatedModel',
    index=0,
    containing_service=None,
    input_type=_UPDATEDMODELREQUEST,
    output_type=_MODELWEIGHTS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_HOSPITAL)

DESCRIPTOR.services_by_name['Hospital'] = _HOSPITAL

# @@protoc_insertion_point(module_scope)
