# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import federated_pb2 as federated__pb2


class HospitalStub(object):
    """Hospital represents a client in our federated learning network. The clients
    are represented as gRPC servers that expose RPC methods.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Initialize = channel.unary_unary(
                '/hospital.Hospital/Initialize',
                request_serializer=federated__pb2.InitializeReq.SerializeToString,
                response_deserializer=federated__pb2.InitializeResp.FromString,
                )
        self.FetchSharedKey = channel.unary_unary(
                '/hospital.Hospital/FetchSharedKey',
                request_serializer=federated__pb2.FetchSharedKeyReq.SerializeToString,
                response_deserializer=federated__pb2.FetchSharedKeyResp.FromString,
                )
        self.ComputeUpdatedModel = channel.unary_unary(
                '/hospital.Hospital/ComputeUpdatedModel',
                request_serializer=federated__pb2.Model.SerializeToString,
                response_deserializer=federated__pb2.TrainedModel.FromString,
                )


class HospitalServicer(object):
    """Hospital represents a client in our federated learning network. The clients
    are represented as gRPC servers that expose RPC methods.
    """

    def Initialize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchSharedKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ComputeUpdatedModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HospitalServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Initialize': grpc.unary_unary_rpc_method_handler(
                    servicer.Initialize,
                    request_deserializer=federated__pb2.InitializeReq.FromString,
                    response_serializer=federated__pb2.InitializeResp.SerializeToString,
            ),
            'FetchSharedKey': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchSharedKey,
                    request_deserializer=federated__pb2.FetchSharedKeyReq.FromString,
                    response_serializer=federated__pb2.FetchSharedKeyResp.SerializeToString,
            ),
            'ComputeUpdatedModel': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeUpdatedModel,
                    request_deserializer=federated__pb2.Model.FromString,
                    response_serializer=federated__pb2.TrainedModel.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hospital.Hospital', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Hospital(object):
    """Hospital represents a client in our federated learning network. The clients
    are represented as gRPC servers that expose RPC methods.
    """

    @staticmethod
    def Initialize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hospital.Hospital/Initialize',
            federated__pb2.InitializeReq.SerializeToString,
            federated__pb2.InitializeResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FetchSharedKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hospital.Hospital/FetchSharedKey',
            federated__pb2.FetchSharedKeyReq.SerializeToString,
            federated__pb2.FetchSharedKeyResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ComputeUpdatedModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hospital.Hospital/ComputeUpdatedModel',
            federated__pb2.Model.SerializeToString,
            federated__pb2.TrainedModel.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
