# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: federated.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='federated.proto',
  package='hospital',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0f\x66\x65\x64\x65rated.proto\x12\x08hospital\"\x18\n\x05Model\x12\x0f\n\x07weights\x18\x01 \x01(\x0c\"H\n\x0cTrainedModel\x12\x1e\n\x05model\x18\x01 \x01(\x0b\x32\x0f.hospital.Model\x12\x18\n\x10training_samples\x18\x02 \x01(\x05\x32L\n\x08Hospital\x12@\n\x13\x43omputeUpdatedModel\x12\x0f.hospital.Model\x1a\x16.hospital.TrainedModel\"\x00\x62\x06proto3'
)




_MODEL = _descriptor.Descriptor(
  name='Model',
  full_name='hospital.Model',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='weights', full_name='hospital.Model.weights', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=53,
)


_TRAINEDMODEL = _descriptor.Descriptor(
  name='TrainedModel',
  full_name='hospital.TrainedModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='hospital.TrainedModel.model', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='training_samples', full_name='hospital.TrainedModel.training_samples', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=127,
)

_TRAINEDMODEL.fields_by_name['model'].message_type = _MODEL
DESCRIPTOR.message_types_by_name['Model'] = _MODEL
DESCRIPTOR.message_types_by_name['TrainedModel'] = _TRAINEDMODEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Model = _reflection.GeneratedProtocolMessageType('Model', (_message.Message,), {
  'DESCRIPTOR' : _MODEL,
  '__module__' : 'federated_pb2'
  # @@protoc_insertion_point(class_scope:hospital.Model)
  })
_sym_db.RegisterMessage(Model)

TrainedModel = _reflection.GeneratedProtocolMessageType('TrainedModel', (_message.Message,), {
  'DESCRIPTOR' : _TRAINEDMODEL,
  '__module__' : 'federated_pb2'
  # @@protoc_insertion_point(class_scope:hospital.TrainedModel)
  })
_sym_db.RegisterMessage(TrainedModel)



_HOSPITAL = _descriptor.ServiceDescriptor(
  name='Hospital',
  full_name='hospital.Hospital',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=129,
  serialized_end=205,
  methods=[
  _descriptor.MethodDescriptor(
    name='ComputeUpdatedModel',
    full_name='hospital.Hospital.ComputeUpdatedModel',
    index=0,
    containing_service=None,
    input_type=_MODEL,
    output_type=_TRAINEDMODEL,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HOSPITAL)

DESCRIPTOR.services_by_name['Hospital'] = _HOSPITAL

# @@protoc_insertion_point(module_scope)
