# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import federated_pb2 as federated__pb2


class FederatedStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUpdatedModel = channel.unary_unary(
                '/federated.Federated/GetUpdatedModel',
                request_serializer=federated__pb2.UpdatedModelRequest.SerializeToString,
                response_deserializer=federated__pb2.ModelWeights.FromString,
                )


class FederatedServicer(object):
    """The greeting service definition.
    """

    def GetUpdatedModel(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FederatedServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUpdatedModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUpdatedModel,
                    request_deserializer=federated__pb2.UpdatedModelRequest.FromString,
                    response_serializer=federated__pb2.ModelWeights.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'federated.Federated', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Federated(object):
    """The greeting service definition.
    """

    @staticmethod
    def GetUpdatedModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/federated.Federated/GetUpdatedModel',
            federated__pb2.UpdatedModelRequest.SerializeToString,
            federated__pb2.ModelWeights.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
